window.SUMMER_CLOUD_CONFIG = Object.freeze({
  supabaseUrl: 'https://ajwqilzvgagaswhpdtul.supabase.co',
  supabasePublishableKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqd3FpbHp2Z2FnYXN3aHBkdHVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU4Nzk1NzcsImV4cCI6MjEwMTQ1NTU3N30.a_OT1VrIj8OnGCduvoSiyKABnmsfnZwuBWrHi0VyLDE',
  supabaseServiceRoleKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqd3FpbHp2Z2FnYXN3aHBkdHVsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NTg3OTU3NywiZXhwIjoyMTAxNDU1NTc3fQ.9maeSJLqMPxCbnB3T0uXsJigcYeTLJx6BD8DS3u7_gA',
  tableName: 'daily_checkins',
  functionName: 'family-sync'
});
